apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
  - name: Loki
    type: loki
    uid: loki
    access: proxy
    url: http://loki:3100
  - name: PostgreSQL
    type: postgres
    uid: postgres
    access: proxy
    url: postgres:5432
    database: invisiblearr
    user: invisiblearr
    jsonData:
      sslmode: disable
      maxOpenConns: 2
      maxIdleConns: 2
    secureJsonData:
      password: $POSTGRES_PASSWORD
